# Generated by Django 3.1.12 on 2021-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210616_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions_role',
            field=models.TextField(null=True),
        ),
    ]
