# Generated by Django 3.1.12 on 2021-06-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210622_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions_role',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
